config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

todo/models.py
from django.db import models

from django.urls import reverse

# Create your models here.
class Task(models.Model):
    class Meta:
      db_table = 'task'

    # statusの選択肢を定義
    OPEN = '新規'
    WORK_IN_PROGRESS = '作業中'
    PENDING = '保留'
    DONE = '完了'
    STATUS = [
      (OPEN, '新規'),
      (WORK_IN_PROGRESS, '作業中'),
      (PENDING, '保留'),
      (DONE, '完了'),
    ]
    title = models.CharField(verbose_name='タイトル', max_length=50)
    content = models.TextField(verbose_name='詳細', max_length=2000)
    status = models.CharField(verbose_name='ステータス', max_length=4,choices=STATUS,default=OPEN)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
      return reverse('todo:index')

todo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Task

# Create your views here.
class TaskListView(ListView):
    model = Task
    template_name = "todo/index.html"
    
index = TaskListView.as_view()

class TaskCreateView(CreateView):
    model = Task
    fields = ("title", "content", "status")
    template_name = "todo/new.html"

new = TaskCreateView.as_view()

class TaskUpdateView(UpdateView):
    model = Task
    fields = ("title", "content", "status")
    template_name = "todo/edit.html"

edit = TaskUpdateView.as_view()

class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('todo:index')
    template_name = "todo/delete.html"

delete = TaskDeleteView.as_view()

templates/base.html
<!DOCTYPE html>

{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<html>
  <head>
    <title>sample todo app</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="{% url 'todo:index' %}">Sample todo app</a>
      </nav>
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

templates/todo/delete.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <div style="margin-top:30px;">
    <form method="post">
      {% csrf_token %}
      <p>削除します。よろしいですか？</p>
      <input class="btn btn-danger" type="submit" value="削除する">
      <a class="btn btn-outline-dark" href="{% url 'todo:index' %}">戻る</a>
    </form>
  </div>
{% endblock  %}

templates/todo/edit.html
{% extends "base.html" %}

{% load static %}
{% load octicons %}

{% block content %}
  <div style="margin-top: 30px;">
    <a class="btn btn-light" href="{% url 'todo:index' %}">{% octicon "reply" %}</a>
  </div>
  <div style="margin-top:30px;">
    <form method="post">
      {% csrf_token %}
      <table>
        {{ form }}
      </table>
      <input type="submit">
    </form>
  </div>
{% endblock  %}
ß

templates/todo/index.html
{% extends "base.html" %}

{% load static %}
{% load octicons %}

{% block content %}
  <div style="margin-top:30px;">
    <a class="btn btn-light" href="{% url 'todo:new' %}">{% octicon "plus" %}</a>
  </div>
  <div style="margin-top:30px;">
    {% if not task_list %}
      <p>まだタスクが登録されていません。</p>
    {% else %}
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">タイトル</th>
            <th scope="col">詳細</th>
            <th scope="col">ステータス</th>
            <th scope="col"></th>
          </tr>        
        </thead>
        <tbody>
          {% for task in task_list %}
            <tr>
              <td>{{ task.id }}</td>
              <td>{{ task.title }}</td>
              <td>{{ task.content }}</td>
              <td>{{ task.status }}</td>
              <td><a class="btn btn-success" href="{% url 'todo:edit' task.id %}">編集</a>　<a class="btn btn-danger" href="{% url 'todo:delete' task.id %}">削除</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
{% endblock %}

templates/todo/new.html
{% extends "base.html" %}

{% load static %}
{% load octicons %}

{% block content %}
  <div style="margin-top: 30px;">
    <a class="btn btn-light" href="{% url 'todo:index' %}">{% octicon "reply" %}</a>
  </div>
  <div style="margin-top:30px;">
    <form method="post">
      {% csrf_token %}
      <table>
        {{ form }}
      </table>
      <input type="submit">
    </form>
  </div>
{% endblock  %}